dist: xenial
sudo: required
language: python
python:
  - 3.7
# Cache Dependencies
cache: pip
addons:
  apt:
    packages:
    - optipng  # for optimize images plugin
    - libjpeg-progs  # for jpegtran for optimize images plugin

before_install:
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - invoke --list
script:
  - invoke publish

deploy:
  provider: pages
  local_dir: output
  target-branch: master
  skip-cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  on:
    branch: source
