permalink: /:year/:month/:title
baseurl: ""
url: https://aviskase.github.io

kramdown:
  input: GFM

gems:
  - jemoji
  - jekyll-sitemap

# Site settings
en:
  title: aviskase
  description: "Simple blog on testing."
  index:
    url: index.html
    title: blog
  about:
    url: about.html
    title: about
  feed: /feed-en.xml
ru:
  title: aviskase
  description: "Простенький бложик о тестировании."
  index:
    url: archive-ru.html
    title: блог
  about:
    url: whois.html
    title: "кто я"
  feed: /feed-ru.xml

email: aviskase@gmail.com
github_username: aviskase
github_repo: "https://github.com/aviskase/aviskase.github.io"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
