baseURL = "https://www.aviskase.com"
languageCode = "en"
title = "aviskase"
buildFuture = true
# canonifyURLs = true
disableKinds = ["section", "taxonomy"]
enableEmoji = true
publishDir = "output"
summaryLength = 50
capitalizeListTitles = false

[taxonomies]
  category = 'categories'


[params]
description = "A blog by Yuliya Bagriy aka aviskase about testing, APIs, and other techy thingies."
images = ["logo.png"]
title = "aviskase"
username = "aviskase"
firstname = "Yuliya"
lastname = "Bagriy"
mainSections = ["posts"]


# [frontmatter]
# date = ["Date", ":default"]
# lastmod = ["Modified", ":default"]

[params.social]
email = "aviskase@gmail.com"
twitter_creator = "@aviskase"

[outputs]
# Output HTML, and ATOM on Home
home = ["HTML", "ATOM"]
# Output only HTML everywhere else
# section = ["HTML"]
# section = ["HTML"]
# taxonomy = ["HTML"]
# term = ["HTML"]

# Define a new ATOM output format
[outputFormats]
[outputFormats.ATOM]
name = "ATOM"
path = "feeds"
baseName = "all"
mediaType = "application/atom+xml"

# Define a new ATOM media type
[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["atom.xml"]



[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.highlight]
style = "catppuccin-mocha"
guessSyntax = true

[markup.goldmark.renderer]
unsafe = true

[permalinks]
articles = "/articles/:year/:month/:day/:slug/"


[menu]
[[menu.main]]
# if you need special typography chars in name, you them as is, because layout page cannot markdownify them
identifier = "home"
name = "Home"
url = "/"
weight = 100

[[menu.main]]
identifier = "rss"
name = "RSS"
url = "/feeds/all.atom.xml"
weight = 300


[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/watching/hugo_stats\.json'
target = 'main\.css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = 'js'
[[build.cachebusters]]
source = 'assets/.*\.(css|scss|sass)'
target = 'css'
[[build.cachebusters]]
source = 'data/.*\.(.*)$'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'